services:
  everything-sse:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: mcp-everything:latest
    command: ["/app/entry-point.sh", "sse"]
    ports:
      - "${MCP_SSE_PORT:-3001}:3001"  # SSE server, configurable via MCP_SSE_PORT

  everything-streamable:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: mcp-everything:latest
    command: ["/app/entry-point.sh", "streamableHttp"]
    ports:
      - "${MCP_STREAMABLE_PORT:-4001}:3001"  # Streamable HTTP server, configurable via MCP_STREAMABLE_PORT

  mcp-inspector:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: mcp-everything:latest
    command: ["/app/entry-point.sh", "inspector"]
    ports:
      - "${MCP_INSPECTOR_PORT:-6274}:6274"  # Inspector GUI, configurable via MCP_INSPECTOR_PORT
      - "${MCP_INSPECTOR_WS_PORT:-6277}:6277"  # Inspector WebSocket, configurable via MCP_INSPECTOR_WS_PORT


