volumes:
  postgres:
  pgadmin:

services:
  # MCP Services
  everything-sse:
    profiles: ["mcp"]
    build:
      context: ./docker/mcp
      dockerfile: Dockerfile
    image: mcp-everything:latest
    command: ["/app/entry-point.sh", "sse"]
    ports:
      - "${MCP_SSE_PORT:-3001}:3001"  # SSE server, configurable via MCP_SSE_PORT

  everything-streamable:
    profiles: ["mcp"]
    build:
      context: ./docker/mcp
      dockerfile: Dockerfile
    image: mcp-everything:latest
    command: ["/app/entry-point.sh", "streamableHttp"]
    ports:
      - "${MCP_STREAMABLE_PORT:-4001}:3001"  # Streamable HTTP server, configurable via MCP_STREAMABLE_PORT

  mcp-inspector:
    profiles: ["mcp"]
    build:
      context: ./docker/mcp
      dockerfile: Dockerfile
    image: mcp-everything:latest
    command: ["/app/entry-point.sh", "inspector"]
    ports:
      - "${MCP_INSPECTOR_PORT:-6274}:6274"  # Inspector GUI, configurable via MCP_INSPECTOR_PORT
      - "${MCP_INSPECTOR_WS_PORT:-6277}:6277"  # Inspector WebSocket, configurable via MCP_INSPECTOR_WS_PORT

  # PostgreSQL Services
  postgres:
    profiles: ["postgres"]
    image: "postgres:17"
    container_name: mcp_postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${PG_PORT:-15432}:5432"  # PostgreSQL port, configurable via PG_PORT
    restart: unless-stopped

  pgadmin:
    profiles: ["postgres"]
    image: "dpage/pgadmin4:9.6"
    container_name: mcp_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./docker/postgres/pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT:-15433}:80"  # pgAdmin port, configurable via PGADMIN_PORT
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'postgres:5432:*:postgres:password' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    restart: unless-stopped


