apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
  - path: resources/servers
    contents:
      - path: .
        git:
          url: https://github.com/modelcontextprotocol/servers.git
          ref: main

  - path: resources/inspector
    contents:
      - path: .
        git:
          url: https://github.com/modelcontextprotocol/inspector.git
          ref: main

  - path: resources/spec
    contents:
      - path: .
        git:
          url: https://github.com/modelcontextprotocol/modelcontextprotocol.git
          ref: 2025-06-18

  - path: resources/java-sdk
    contents:
      - path: .
        git:
          url: https://github.com/modelcontextprotocol/java-sdk
          ref: v0.11.1
