apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
  - path: test/servers
    contents:
      - path: .
        git:
          url: https://github.com/modelcontextprotocol/servers.git
          ref: main

  - path: test/inspector
    contents:
      - path: .
        git:
          url: https://github.com/modelcontextprotocol/inspector.git
          ref: main
